config/routes.rb
Rails.application.routes.draw do
  root 'gossips#index'
  get 'welcome/:first_name', to: 'welcome#user'
  get '/team', to: 'static#team'
  get '/contact', to: 'static#contact'
  resources :gossips do
    resources :comments
    resources :likes, only: %i[new create destroy]
  end
  resources :comments, except: :create do
    resources :comments
    resources :likes, only: %i[new create destroy]
  end
  resources :users do
    resources :likes, only: %i[new create destroy]
  end
  resources :cities, only: [:show] do
    resources :likes, only: %i[new create destroy]
  end
  resources :tags, only: [:show] do
    resources :likes, only: %i[new create destroy]
  end
  resources :sessions, only: %i[new create destroy]
  delete '/logout', to: 'sessions#destroy'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/city.rb
class City < ApplicationRecord
  include Liked

  has_many :users
  has_many :gossips, through: :users
  has_many :likes, as: :likeable, dependent: :destroy
end

app/models/comment.rb
class Comment < ApplicationRecord
  include Liked

  belongs_to :user
  has_many :likes, as: :likeable, dependent: :destroy
  belongs_to :commentable, polymorphic: true
  has_many :comments, as: :commentable, dependent: :destroy
  validates :content, presence: true
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  include Liked

  belongs_to :user
  has_and_belongs_to_many :tags
  has_many :comments, as: :commentable, dependent: :destroy
  has_many :likes, as: :likeable, dependent: :destroy
  validates :title,
            presence: true,
            length: { maximum: 20 }
  validates :content, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :likeable, polymorphic: true
  # validates :user_id, uniqueness: { scope: :likeable_id }
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: 'User'
  has_and_belongs_to_many :recipients, class_name: 'User'
end

app/models/tag.rb
class Tag < ApplicationRecord
  include Liked
  has_and_belongs_to_many :gossips
  has_many :likes, as: :likeable, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  include Liked

  has_many :sent_messages, foreign_key: 'sender_id', class_name: 'PrivateMessage'
  has_and_belongs_to_many :received_messages, class_name: 'PrivateMessage'
  belongs_to :city
  has_many :gossips
  has_many :comments
  has_many :likes
  has_many :likes, as: :likeable, dependent: :destroy
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :description,
            presence: true,
            length: { maximum: 500 }
  validates :email,
            presence: true,
            uniqueness: true,
            format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: 'email adress please' }
  validates :age, presence: true
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, on: :create

  def remember(remember_token)
    remember_digest = BCrypt::Password.create(remember_token)
    update(remember_digest: remember_digest)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_commentable, only: %i[new create]

  def new
    @comment = Comment.new
  end

  def create
    @comment = @commentable.comments.new(comment_params)
    @comment.user = current_user

    if @comment.save
      flash[:success] = 'Votre commentaire a bien été ajouté'
      redirect_to @commentable
    else
      flash[:error] = "Votre commentaire n'a pas pu être créé"
      redirect_back fallback_location: root_path
    end
  end

  def edit
    @comment = Comment.find(params[:id])
    session[:return_to] ||= request.referer
  end

  def update
    @comment = Comment.find(params[:id])

    if @comment.update(comment_params)
      flash[:success] = 'Le commentaire a bien été mis à jour'
      redirect_to session.delete(:return_to)
    else
      flash[:error] = "Le commentaire n'a pas pu être mis à jour"
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    flash[:success] = 'Le commentaire a bien été supprimé'
    redirect_back fallback_location: root_path
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end

  def find_commentable
    @commentable = Comment.find_by_id(params[:comment_id]) if params[:comment_id]
    @commentable = Gossip.find_by_id(params[:gossip_id]) if params[:gossip_id]
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :find_likeable, only: %i[new create destroy]

  def new
    @like = Like.new
  end

  def create
    @like = @likeable.likes.new(user: current_user)
    if @like.save!
      flash[:success] = "Merci d'aimer !"
    else
      flash[:alert] = @like.errors.full_messages.join(', ')
    end
    redirect_back fallback_location: root_path
  end

  def destroy
    @like = @likeable.likes.find_by(user: current_user)
    @like.destroy
    flash[:success] = "Vous n'aimez plus ce contenu !"
    redirect_back fallback_location: root_path
  end

  private

  def find_likeable
    @likeable = Comment.find_by_id(params[:comment_id]) if params[:comment_id]
    @likeable = Gossip.find_by_id(params[:gossip_id]) if params[:gossip_id]
    @likeable = User.find_by_id(params[:user_id]) if params[:user_id]
    @likeable = Tag.find_by_id(params[:tag_id]) if params[:tag_id]
    @likeable = City.find_by_id(params[:city_id]) if params[:city_id]
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def show
    @tag = Tag.find(params[:id])
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def show
    @user = User.find(params['id'])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      log_in(@user)
      remember(@user) if params[:user][:remember_user] == '1'
      flash[:success] = 'Votre compte a bien été créé'
      redirect_to root_path
    else
      flash[:error] = "Votre compte n'a pas pu être créé"
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @user = User.find(params['id'])
  end

  private

  def user_params
    params.require(:user).permit(:first_name,
                                 :last_name,
                                 :age,
                                 :email,
                                 :password,
                                 :password_confirmation,
                                 :city_id, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    if session[:user_id]
      current_user = User.find_by(id: session[:user_id])
    elsif cookies[:user_id]
      user = User.find_by(id: cookies[:user_id])
      if user && BCrypt::Password.new(user.remember_digest).is_password?(cookies[:remember_token])
        log_in(user)
        current_user = user
      end
    end
  end

  def log_in(user)
    session[:user_id] = user.id
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out(user)
    session.delete(:user_id)
    forget(user)
    @current_user = nil
  end

  def remember(user)
    remember_token = SecureRandom.urlsafe_base64
    user.remember(remember_token)
    cookies.permanent[:user_id] = user.id
    cookies.permanent[:remember_token] = remember_token
  end

  def forget(user)
    user.update(remember_digest: nil)
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/_comment.html.erb
<li>
  <div class="overflow-scroll text-wrap">
    <%= comment.content %>
  </div>
  <div class="container d-flex p-0 my-1 align-items-center">
    <strong class="mx-1"><%= comment.user.first_name %></strong>
    <small class="mx-1">Le <%= comment.created_at.strftime('%d/%m/%y à %k:%M') %></small>
    <% if logged_in? %>
      <% if current_user == comment.user %>
        <div class="btn-group mx-1">
          <%= link_to "Editer", edit_comment_path(comment.id), class: "btn btn-sm btn-primary" %> 
          <%= link_to "Supprimer", comment_path(comment.id), data: { turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "btn btn-sm btn-danger" %>
        </div>
      <% end %>
      <div class="btn-group mx-1" role="groupe" aria-label="like and comment">
        <%= render partial: 'like_buttons', locals: { object: comment, path: 'comment_likes_path', delete_path: 'comment_like_path' } %>
        <span class="dropdown">
          <button type="button" class="btn btn-sm btn-outline-primary dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false" data-bs-auto-close="outside">
            <i class="fa-solid fa-comments"></i>
          </button>
          <%= form_for [comment, Comment.new], :html => {:class => "dropdown-menu"} do |form|%>
            <div class="mb-3">
              <%= form.label 'Commenter' %><br>
              <%= form.text_area :content, placeholder: "Ajoutez un commentaire" %>
              <% @comment.errors.full_messages_for(:content).each do |message| %>
                <div><%= message %></div>
              <% end %>
            </div>
            <div>
              <%= form.submit "Commenter" %>
            </div>
          <% end %>
        </span>
      </div>
    <% end %>
  </div>  

  <ul>
    <%= render comment.comments %>
  </ul>
</li>

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

app/views/comments/edit.html.erb
<h1>Edite le commentaire</h1>

<%= form_with model: @comment do |form|%>
  <div class="mb-3">
    <%= form.label :content %><br>
    <%= form.text_area :content %>
    <% @comment.errors.full_messages_for(:content).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/new.html.erb
<h1>Nouveau commentaire</h1>

<%= form_with model: @comment do |form|%>
  <div class="mb-3">
    <%= form.label :content %><br>
    <%= form.text_area :content %>
    <% @comment.errors.full_messages_for(:content).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/update.html.erb
<h1>Comments#update</h1>
<p>Find me in app/views/comments/update.html.erb</p>