config/routes.rb
Rails.application.routes.draw do
  root 'gossips#index'
  get 'welcome/:first_name', to: 'welcome#user'
  get '/team', to: 'static#team'
  get '/contact', to: 'static#contact'
  resources :gossips do
    resources :comments
    resources :likes, only: %i[new create destroy]
  end
  resources :comments, except: :create do
    resources :comments
    resources :likes, only: %i[new create destroy]
  end
  resources :users do
    resources :likes, only: %i[new create destroy]
  end
  resources :cities, only: [:show] do
    resources :likes, only: %i[new create destroy]
  end
  resources :tags, only: [:show] do
    resources :likes, only: %i[new create destroy]
  end
  resources :sessions, only: %i[new create destroy]
  delete '/logout', to: 'sessions#destroy'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/city.rb
class City < ApplicationRecord
  include Liked

  has_many :users
  has_many :gossips, through: :users
  has_many :likes, as: :likeable, dependent: :destroy
end

app/models/comment.rb
class Comment < ApplicationRecord
  include Liked

  belongs_to :user
  has_many :likes, as: :likeable, dependent: :destroy
  belongs_to :commentable, polymorphic: true
  has_many :comments, as: :commentable, dependent: :destroy
  validates :content, presence: true
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  include Liked

  belongs_to :user
  has_and_belongs_to_many :tags
  has_many :comments, as: :commentable, dependent: :destroy
  has_many :likes, as: :likeable, dependent: :destroy
  validates :title,
            presence: true,
            length: { maximum: 20 }
  validates :content, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :likeable, polymorphic: true
  # validates :user_id, uniqueness: { scope: :likeable_id }
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: 'User'
  has_and_belongs_to_many :recipients, class_name: 'User'
end

app/models/tag.rb
class Tag < ApplicationRecord
  include Liked
  has_and_belongs_to_many :gossips
  has_many :likes, as: :likeable, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  include Liked

  has_many :sent_messages, foreign_key: 'sender_id', class_name: 'PrivateMessage'
  has_and_belongs_to_many :received_messages, class_name: 'PrivateMessage'
  belongs_to :city
  has_many :gossips
  has_many :comments
  has_many :likes
  has_many :likes, as: :likeable, dependent: :destroy
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :description,
            presence: true,
            length: { maximum: 500 }
  validates :email,
            presence: true,
            uniqueness: true,
            format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: 'email adress please' }
  validates :age, presence: true
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, on: :create

  def remember(remember_token)
    remember_digest = BCrypt::Password.create(remember_token)
    update(remember_digest: remember_digest)
  end
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
  before_action :authenticate_user, only: %i[new create]

  def index
    @gossips = Gossip.all.sort_by(&:created_at)
  end

  def show
    @gossip = Gossip.find(params['id'])
    @comment = Comment.new
  end

  def new
    @gossip = Gossip.new
  end

  def create
    @gossip = Gossip.new(gossip_params)
    @gossip.user = current_user

    if @gossip.save
      flash[:success] = 'Votre potin a bien été ajouté'
      redirect_to action: 'index'
    else
      flash[:error] = "Votre potin n'a pas pu être créé"
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @gossip = Gossip.find(params['id'])

    return if user_allowed_to_edit?

    flash[:error] = "Seul l'auteur du potin peut le modifier"
    render :show
  end

  def update
    @gossip = Gossip.find(params[:id])

    if user_allowed_to_edit?
      if @gossip.update(gossip_params)
        flash[:success] = 'Le potin a bien été mis à jour'
        redirect_to @gossip
      else
        flash[:error] = "Le potin n'a pas pu être mis à jour"
        render :edit, status: :unprocessable_entity
      end
    else
      flash[:error] = "Seul l'auteur du potin peut le modifier"
      render :show
    end
  end

  def destroy
    @gossip = Gossip.find(params[:id])

    if user_allowed_to_edit?
      @gossip.destroy
      flash[:success] = 'Le potin a bien été supprimé'
      redirect_to action: 'index'
    else
      flash[:error] = "Seul l'auteur du potin peut le modifier"
      render :show
    end
  end

  private

  def gossip_params
    params.require(:gossip).permit(:title, :content, tag_ids: [])
  end

  def authenticate_user
    return if current_user

    flash[:alert] = 'Veuillez vous connecter'
    redirect_to new_session_path
  end

  def user_allowed_to_edit?
    current_user == @gossip.user
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :find_likeable, only: %i[new create destroy]

  def new
    @like = Like.new
  end

  def create
    @like = @likeable.likes.new(user: current_user)
    if @like.save!
      flash[:success] = "Merci d'aimer !"
    else
      flash[:alert] = @like.errors.full_messages.join(', ')
    end
    redirect_back fallback_location: root_path
  end

  def destroy
    @like = @likeable.likes.find_by(user: current_user)
    @like.destroy
    flash[:success] = "Vous n'aimez plus ce contenu !"
    redirect_back fallback_location: root_path
  end

  private

  def find_likeable
    @likeable = Comment.find_by_id(params[:comment_id]) if params[:comment_id]
    @likeable = Gossip.find_by_id(params[:gossip_id]) if params[:gossip_id]
    @likeable = User.find_by_id(params[:user_id]) if params[:user_id]
    @likeable = Tag.find_by_id(params[:tag_id]) if params[:tag_id]
    @likeable = City.find_by_id(params[:city_id]) if params[:city_id]
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def show
    @tag = Tag.find(params[:id])
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def show
    @user = User.find(params['id'])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      log_in(@user)
      remember(@user) if params[:user][:remember_user] == '1'
      flash[:success] = 'Votre compte a bien été créé'
      redirect_to root_path
    else
      flash[:error] = "Votre compte n'a pas pu être créé"
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @user = User.find(params['id'])
  end

  private

  def user_params
    params.require(:user).permit(:first_name,
                                 :last_name,
                                 :age,
                                 :email,
                                 :password,
                                 :password_confirmation,
                                 :city_id, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    if session[:user_id]
      current_user = User.find_by(id: session[:user_id])
    elsif cookies[:user_id]
      user = User.find_by(id: cookies[:user_id])
      if user && BCrypt::Password.new(user.remember_digest).is_password?(cookies[:remember_token])
        log_in(user)
        current_user = user
      end
    end
  end

  def log_in(user)
    session[:user_id] = user.id
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out(user)
    session.delete(:user_id)
    forget(user)
    @current_user = nil
  end

  def remember(user)
    remember_token = SecureRandom.urlsafe_base64
    user.remember(remember_token)
    cookies.permanent[:user_id] = user.id
    cookies.permanent[:remember_token] = remember_token
  end

  def forget(user)
    user.update(remember_digest: nil)
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/gossips/edit.html.erb
<h1>Edite le potin</h1>

<% @gossip.errors do |error| %>
  <%= error %>
<% end %>

<%= form_with model: @gossip do |form|%>
  <div class="mb-3">
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% @gossip.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div class="mb-3">
    <%= form.label :content %><br>
    <%= form.text_area :content %>
    <% @gossip.errors.full_messages_for(:content).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div class="mb-3">
    <%= form.label :tag %><br>
    <%= form.collection_check_boxes :tag_ids, Tag.order(:title), :id, :title, {}, { :multiple => true } %>
    <% @gossip.errors.full_messages_for(:tag).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/gossips/index.html.erb
<h1 class="my-3">Tous les potins !</h1>
<% if @gossips.empty? %>
  <div>
    Il semblerait qu'il n'y ait aucun potin pour le moment... Connecte-toi vite pour bitcher sur tes amis !
  </div>
<% end %>
<%@gossips.in_groups_of(4) do |group|%>
  <div class="row row-cols-1 row-cols-sm-2 row-cols-lg-4 g-3 text-center mt-3">
    <%group.each do |gossip|%>
      <%unless gossip.nil?%>
        <div class="col py-1">
          <div class="card" >
            <h6 class="card-header text-muted">
              <a href="<%= gossip_path(gossip) %>" class="stretched-link text-decoration-none mb-1"><%= gossip.title %></a>
              <div>Selon <%=gossip.user.first_name%>...</div>
            </h6>
            <div class="card-body pb-2">
              <p class="card-text text-truncate mb-1"><%= gossip.content %></p>
              <div class="btn-group my-1" role="group" aria-label="Like and comment">
                <%= render partial: 'like_buttons', locals: { object: gossip, path: "gossip_likes_path", delete_path: "gossip_like_path" } %>
                <%= render partial: 'comment_buttons', locals: { object: gossip } %>
              </div>
              <div>
                <% gossip.tags[0..2].each do |tag| %>
                  <%= link_to tag.title, tag, class: "link-secondary" %>
                <% end %>
                <% if gossip.tags.count > 3 %>
                  <%= "et #{gossip.tags.count - 3} autre" + (gossip.tags.count == 4 ? "" : "s") %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      <%end%>
    <%end%>
  </div>
<%end%>

app/views/gossips/new.html.erb
<h1>Nouveau potin</h1>

<%= form_with model: @gossip do |form|%>
  <div class="mb-3">
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% @gossip.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div class="mb-3">
    <%= form.label :content %><br>
    <%= form.text_area :content %>
    <% @gossip.errors.full_messages_for(:content).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div class="mb-3">
    <%= form.label :tag %><br>
    <%= form.collection_check_boxes :tag_ids, Tag.order(:title), :id, :title, {}, { :multiple => true, :class => "d-inline-flex" }  %>
    <% @gossip.errors.full_messages_for(:tag).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>


  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/gossips/show.html.erb
<div class="container d-flex flex-column align-items-stretch">
  <h1 class="text-center mb-3">
    <%= @gossip.title %>
    <%= render partial: 'like_buttons', locals: { object: @gossip, path: "gossip_likes_path", delete_path: "gossip_like_path"} %>
  </h1>

  <p class="mb-1">
    <% @gossip.tags.sort_by(&:title).each do |tag| %>
      <%= link_to tag.title, tag %>
    <% end %>
  <p> 
    Par <%= link_to "#{@gossip.user.first_name} #{@gossip.user.last_name}", user_path(@gossip.user.id) %> 
    (<%= link_to @gossip.user.city.name, city_path(@gossip.user.city.id) %>)
  </p>
  <div class="my-2"><%= @gossip.content %></div>
  <div class="my-2"><small>  Posté le <%= @gossip.created_at.strftime('%d/%m/%y') %> à <%= @gossip.created_at.strftime('%k:%M') %></small></div>

  <h5> Commentaires </h5>

  <% if @gossip.comments.empty? %>
    <div> Aucun commentaire... pour le moment !</div>
  <% end %>

  <ul>
    <%= render @gossip.comments %>
  </ul>

  <% if logged_in? %>
    <%= form_for [@gossip, Comment.new] do |form|%>
      <div class="mb-2">
        <h6><%= form.label 'Commenter' %></h6>
        <%= form.text_area :content, placeholder: "Qu'en pensez-vous ?" %>
        <% @comment.errors.full_messages_for(:content).each do |message| %>
          <div><%= message %></div>
        <% end %>
      </div>

      <div>
        <%= form.submit "Commenter", class: "btn btn-primary" %>
      </div>
    <% end %>
  <% end %>

  <h5 class="mt-4">Likes</h5>

  <% unless @gossip.likes.empty? %>
    <span>
      Liké par :
      <%= @gossip.likes.sort_by(&:created_at).map { |like| like.user.first_name }.join(', ') %>
    </span>
  <% end %>

    

  <% if current_user == @gossip.user %>
    <div class="mt-2">
      <%= link_to "Editer le potin", edit_gossip_path %>
      <%= link_to "Supprimer le potin", gossip_path(@gossip), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
    </div>
  <% end %>
</div>