config/routes.rb
Rails.application.routes.draw do
  root 'gossips#index'
  get 'welcome/:first_name', to: 'welcome#user'
  get '/team', to: 'static#team'
  get '/contact', to: 'static#contact'
  resources :gossips do
    resources :comments
    resources :likes, only: %i[new create destroy]
  end
  resources :comments, except: :create do
    resources :comments
    resources :likes, only: %i[new create destroy]
  end
  resources :users do
    resources :likes, only: %i[new create destroy]
  end
  resources :cities, only: [:show] do
    resources :likes, only: %i[new create destroy]
  end
  resources :tags, only: [:show] do
    resources :likes, only: %i[new create destroy]
  end
  resources :sessions, only: %i[new create destroy]
  delete '/logout', to: 'sessions#destroy'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/city.rb
class City < ApplicationRecord
  include Liked

  has_many :users
  has_many :gossips, through: :users
  has_many :likes, as: :likeable, dependent: :destroy
end

app/models/comment.rb
class Comment < ApplicationRecord
  include Liked

  belongs_to :user
  has_many :likes, as: :likeable, dependent: :destroy
  belongs_to :commentable, polymorphic: true
  has_many :comments, as: :commentable, dependent: :destroy
  validates :content, presence: true
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  include Liked

  belongs_to :user
  has_and_belongs_to_many :tags
  has_many :comments, as: :commentable, dependent: :destroy
  has_many :likes, as: :likeable, dependent: :destroy
  validates :title,
            presence: true,
            length: { maximum: 20 }
  validates :content, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :likeable, polymorphic: true
  # validates :user_id, uniqueness: { scope: :likeable_id }
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: 'User'
  has_and_belongs_to_many :recipients, class_name: 'User'
end

app/models/tag.rb
class Tag < ApplicationRecord
  include Liked
  has_and_belongs_to_many :gossips
  has_many :likes, as: :likeable, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  include Liked

  has_many :sent_messages, foreign_key: 'sender_id', class_name: 'PrivateMessage'
  has_and_belongs_to_many :received_messages, class_name: 'PrivateMessage'
  belongs_to :city
  has_many :gossips
  has_many :comments
  has_many :likes
  has_many :likes, as: :likeable, dependent: :destroy
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :description,
            presence: true,
            length: { maximum: 500 }
  validates :email,
            presence: true,
            uniqueness: true,
            format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: 'email adress please' }
  validates :age, presence: true
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, on: :create

  def remember(remember_token)
    remember_digest = BCrypt::Password.create(remember_token)
    update(remember_digest: remember_digest)
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def show
    @tag = Tag.find(params[:id])
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def show
    @user = User.find(params['id'])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    if session[:user_id]
      current_user = User.find_by(id: session[:user_id])
    elsif cookies[:user_id]
      user = User.find_by(id: cookies[:user_id])
      if user && BCrypt::Password.new(user.remember_digest).is_password?(cookies[:remember_token])
        log_in(user)
        current_user = user
      end
    end
  end

  def log_in(user)
    session[:user_id] = user.id
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out(user)
    session.delete(:user_id)
    forget(user)
    @current_user = nil
  end

  def remember(user)
    remember_token = SecureRandom.urlsafe_base64
    user.remember(remember_token)
    cookies.permanent[:user_id] = user.id
    cookies.permanent[:remember_token] = remember_token
  end

  def forget(user)
    user.update(remember_digest: nil)
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheGossipProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class="navbar navbar-expand-sm navbar-dark bg-dark" data-bs-theme="dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">The Gossip Project</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-0 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="<%=gossips_path%>">Tous les potins</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="<%=team_path%>">Team</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="<%=contact_path%>">Contact</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="<%=new_gossip_path%>">Créer un potin</a>
            </li>
            <% if logged_in? %>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false" data-turbo-disabled='true'>
                  <%= current_user.first_name %>
                </a>
                <ul class="dropdown-menu">
                  <li><a class="nav-link" href="<%=user_path(current_user)%>">Mon compte</a></li>
                  <li><%= link_to "Se déconnecter", logout_path, class: "nav-link", data: { turbo_method: :delete } %></li>
                </ul>
              </li>
            <% else %>
              <li class="nav-item">
                <a class="nav-link" href="<%=new_session_path %>">Se connecter</a>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
    <%= render 'application/flashes' %>
    <div class="container mt-4">
      <%= yield %>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
  </body>
</html>